name = "arxiv-summarizer-worker"
main = "src/index.ts"
compatibility_date = "2024-11-08"

[vars]
# Set via `wrangler secret put GOOGLE_API_KEY`
# GOOGLE_API_KEY = ""
ALLOWED_ORIGINS = "https://rvpanchani.github.io, http://localhost:5173, https://arxiv-summarizer.vercel.app, http://localhost:5174"